name: Hello World Workflow

on: 
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: self-hosted label-1 my-first-runner
    # This specifies that the job should run on your self-hosted runner with the specified labels

    steps:
    - name: Echo Hello World
      run: echo "Hello World!!"
